name: Test

on:
  issues:
    types: [opened, edited, deleted, transferred, pinned, unpinned, closed, reopened, assigned, unassigned, labeled, unlabeled, locked, unlocked, milestoned, demilestoned]
  pull_request:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed, auto_merge_enabled, auto_merge_disabled]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
    - name: Sync Github PRs to Notion
      uses: sivashanmukh/github-notion-pr-sync@0.0.7-beta
      with:
        notionKey: ${{ secrets.NOTION_BOT_TOKEN }}
        notionDatabaseId: 3c5d5636129f456b99588d55ac4aa69f
        githubKey: ${{ secrets.PAT }}
